project:
  type: website
  output-dir: docs

website:
  title: "Nicholas Burk"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd

format:
  html:
    theme: 
      - darkly
      - custom.scss
    css: styles.css
    toc: true

editor: visual

